name: Deploy OpenFaaS Functions

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install faas-cli
      run: |
        curl -sSL https://cli.openfaas.com | sudo sh

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        
      run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

    - name: Build, push and deploy functions with prune
      env:
        OPENFAAS_GATEWAY: ${{ secrets.OPENFAAS_GATEWAY }}
        OPENFAAS_USER: ${{ secrets.OPENFAAS_USERNAME }}
        OPENFAAS_PASSWORD: ${{ secrets.OPENFAAS_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: |
        echo $OPENFAAS_PASSWORD | faas-cli login --username $OPENFAAS_USER --password-stdin --gateway $OPENFAAS_GATEWAY
        faas-cli up -f deploy.yml --replace
